using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class BillIndex
    {
        public decimal BillNumberId { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillCode { get; set; }
        public decimal BillType { get; set; }
        public string Comment { get; set; }
        public string atypeid { get; set; }
        public string ptypeid { get; set; }
        public string btypeid { get; set; }
        public string etypeid { get; set; }
        public string ktypeid { get; set; }
        public string ktypeid2 { get; set; }
        public string ifcheck { get; set; }
        public string checke { get; set; }
        public Nullable<decimal> totalmoney { get; set; }
        public Nullable<decimal> totalinmoney { get; set; }
        public Nullable<decimal> totalqty { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<short> period { get; set; }
        public string explain { get; set; }
        public int RedWord { get; set; }
        public bool draft { get; set; }
        public Nullable<decimal> OrderId { get; set; }
        public string waybillcode { get; set; }
        public string goodsnumber { get; set; }
        public string packway { get; set; }
        public string TEL { get; set; }
        public bool Uploaded { get; set; }
        public Nullable<System.Guid> OFF_ID { get; set; }
        public Nullable<int> TeamNo { get; set; }
        public Nullable<int> AlertDay { get; set; }
        public Nullable<decimal> CompleteTotal { get; set; }
        public decimal ID { get; set; }
        public string Assessor { get; set; }
        public string IfAudit { get; set; }
        public string Audit_explain { get; set; }
        public string IfStopMoney { get; set; }
        public Nullable<decimal> preferencemoney { get; set; }
        public string DTypeId { get; set; }
        public Nullable<int> JF { get; set; }
        public Nullable<int> VipCardID { get; set; }
        public Nullable<decimal> vipCZMoney { get; set; }
        public string jsStyle { get; set; }
        public string jsState { get; set; }
        public string KTypeID3 { get; set; }
        public string LinkMan { get; set; }
        public string LinkTel { get; set; }
        public string LinkAddr { get; set; }
        public string wxManID { get; set; }
        public Nullable<int> JieJianBillNumberID { get; set; }
        public Nullable<int> JieJianID { get; set; }
        public Nullable<int> JieJianState { get; set; }
        public Nullable<int> BaoXiuBillNumberID { get; set; }
        public Nullable<int> BaoXiuID { get; set; }
        public string BuyDate { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> wxTotal { get; set; }
        public string ErrDes { get; set; }
        public Nullable<int> ifHideJieJian { get; set; }
        public Nullable<int> ifWX { get; set; }
        public Nullable<int> ifYearBill { get; set; }
        public string Poster { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Stypeid { get; set; }
        public Nullable<decimal> FromBillNumberID { get; set; }
        public Nullable<bool> CostSale { get; set; }
        public Nullable<int> OtherInOutType { get; set; }
        public Nullable<int> PosBillType { get; set; }
        public Nullable<System.DateTime> checkTime { get; set; }
        public Nullable<System.DateTime> posttime { get; set; }
        public string updateE { get; set; }
        public Nullable<byte> ShareMode { get; set; }
        public string TransportId { get; set; }
        public Nullable<bool> IsIni { get; set; }
        public string ATypeID1 { get; set; }
        public Nullable<decimal> NCompleteTotal { get; set; }
        public Nullable<int> ATID { get; set; }
        public Nullable<bool> IfCargo { get; set; }
        public Nullable<decimal> InvoiceMoney { get; set; }
        public Nullable<decimal> NInvoiceMoney { get; set; }
        public Nullable<decimal> NARTotal { get; set; }
        public Nullable<decimal> NAPTotal { get; set; }
        public Nullable<decimal> NYSTotal { get; set; }
        public Nullable<decimal> NYFTotal { get; set; }
        public string RedReason { get; set; }
        public int PrePriceNum { get; set; }
        public Nullable<int> AssetBusinessTypeId { get; set; }
        public int PromoRuleId { get; set; }
        public int BeforePromoBillNumberId { get; set; }
        public byte ImportType { get; set; }
        public Nullable<byte> NewPosBill { get; set; }
        public string PromotionMsg { get; set; }
        public string Reconciliation { get; set; }
        public Nullable<decimal> ARTOTAL { get; set; }
        public Nullable<decimal> APTOTAL { get; set; }
        public Nullable<decimal> YSTOTAL { get; set; }
        public Nullable<decimal> YFTOTAL { get; set; }
        public Nullable<int> IsAuto { get; set; }
        public Nullable<bool> IsYapi { get; set; }
        public Nullable<decimal> YapiOrderID { get; set; }
        public string DeliveryAddress { get; set; }
        public int AddDTypeETypeType { get; set; }
        public string BillTime { get; set; }
        public int CWCheck { get; set; }
        public Nullable<int> IfBargainOn { get; set; }
        public Nullable<int> IfMulAccount { get; set; }
        public Nullable<int> IsFreightMoney { get; set; }
        public string FreightAddr { get; set; }
        public string FreightPerson { get; set; }
        public string FreightTel { get; set; }
        public Nullable<int> IfInvoice { get; set; }
        public string UF1 { get; set; }
        public string UF2 { get; set; }
        public string UF3 { get; set; }
        public string UF4 { get; set; }
        public string UF5 { get; set; }
        public string DealBTypeID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> NTotalMoney { get; set; }
        public Nullable<decimal> NTotalInMoney { get; set; }
        public Nullable<decimal> NPreferenceMoney { get; set; }
        public Nullable<decimal> NVIPCZMoney { get; set; }
        public Nullable<int> billproperty { get; set; }
        public string TallyId { get; set; }
        public string StypeID2 { get; set; }
        public int IfConfirm { get; set; }
        public int TransferType { get; set; }
        public int FeeDeductType { get; set; }
        public Nullable<bool> IsLend { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public byte AdPriceType { get; set; }
        public string ChargeOffBtypeid { get; set; }
        public int ChargeOffType { get; set; }
        public Nullable<decimal> ChargeOffTotal { get; set; }
        public Nullable<decimal> NChargeOffTotal { get; set; }
        public string cwchecker { get; set; }
    }
}
