using System;
using System.Collections.Generic;

namespace Test.Models
{
    public partial class vWeb_AdPriceBill
    {
        public decimal BillNumberId { get; set; }
        public string @base { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> beforeprice { get; set; }
        public Nullable<decimal> NTotal { get; set; }
        public Nullable<decimal> NPrice { get; set; }
        public Nullable<int> frombillid { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> beforetotal { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string ProduceDate { get; set; }
        public string ValidDate { get; set; }
        public string GoodsNumber { get; set; }
        public Nullable<decimal> GoodsCostPrice { get; set; }
        public Nullable<int> HandZeroCost { get; set; }
        public string PtypeId { get; set; }
        public int IsUnit2 { get; set; }
        public Nullable<int> ChangeAllStock { get; set; }
        public int ID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string itemname { get; set; }
        public Nullable<int> iscombined { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> NUnitID { get; set; }
        public string unit { get; set; }
        public string nunit { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<decimal> NQty { get; set; }
        public Nullable<int> cargoID { get; set; }
        public string cargofullname { get; set; }
        public string ktypeid { get; set; }
        public string kfullname { get; set; }
        public string frombillnumberusercode { get; set; }
        public Nullable<int> FromBillNumberId { get; set; }
        public string serial { get; set; }
        public string typeId { get; set; }
        public string ParId { get; set; }
        public short leveal { get; set; }
        public int sonnum { get; set; }
        public int soncount { get; set; }
        public string CanModify { get; set; }
        public string UserCode { get; set; }
        public string FullName { get; set; }
        public string Name { get; set; }
        public string Standard { get; set; }
        public string Type { get; set; }
        public string Area { get; set; }
        public string Unit1 { get; set; }
        public string Unit2 { get; set; }
        public Nullable<decimal> UnitRate1 { get; set; }
        public Nullable<decimal> UnitRate2 { get; set; }
        public Nullable<decimal> preprice1 { get; set; }
        public Nullable<decimal> preprice2 { get; set; }
        public Nullable<decimal> preprice3 { get; set; }
        public Nullable<decimal> preprice4 { get; set; }
        public Nullable<decimal> preprice5 { get; set; }
        public Nullable<short> UsefulLifeMonth { get; set; }
        public Nullable<short> UsefulLifeDay { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> recPrice { get; set; }
        public bool deleted { get; set; }
        public Nullable<int> ColorGroupID { get; set; }
        public Nullable<int> SizeGroupID { get; set; }
        public string EntryCode { get; set; }
        public string IfSerial { get; set; }
        public string PyCode { get; set; }
        public Nullable<int> SerialCount { get; set; }
        public Nullable<int> ValidDays { get; set; }
        public Nullable<decimal> XiWaMaxNumber { get; set; }
        public string DwgNo { get; set; }
        public string ImgURL { get; set; }
        public Nullable<bool> IsDownLoad { get; set; }
        public byte[] PosDataVersion { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int IsService { get; set; }
        public int SortID { get; set; }
        public Nullable<bool> OmUse { get; set; }
        public Nullable<decimal> OmPrice { get; set; }
        public Nullable<decimal> BuyDefaultRate { get; set; }
        public Nullable<decimal> SaleDefaultRate { get; set; }
        public Nullable<decimal> Integral { get; set; }
        public Nullable<int> StopBuy { get; set; }
        public Nullable<int> IsOm { get; set; }
        public string customitemid { get; set; }
        public string customitemfrom { get; set; }
        public string customitemname { get; set; }
        public string customitemrefid { get; set; }
        public Nullable<int> UnitsType { get; set; }
        public Nullable<int> AssistantUnitId { get; set; }
        public Nullable<int> SaleUnitId { get; set; }
        public Nullable<int> BuyUnitId { get; set; }
        public Nullable<int> ProduceUnitId { get; set; }
        public Nullable<int> StockUnitId { get; set; }
        public Nullable<int> JobUnitId { get; set; }
        public Nullable<int> baseUnitId { get; set; }
        public Nullable<bool> IfUseEntryCode { get; set; }
        public Nullable<bool> IfUseGoodsNum { get; set; }
        public int Pid { get; set; }
        public Nullable<bool> isyapi { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> Detailid { get; set; }
        public Nullable<int> BillType { get; set; }
        public string SysDiy1 { get; set; }
        public string SysDiy2 { get; set; }
        public string SysDiy3 { get; set; }
        public string SysDiy4 { get; set; }
        public string SysDiy5 { get; set; }
        public Nullable<decimal> SysDiy6 { get; set; }
        public Nullable<decimal> SysDiy7 { get; set; }
        public Nullable<decimal> SysDiy8 { get; set; }
        public Nullable<decimal> SysDiy9 { get; set; }
        public Nullable<decimal> SysDiy10 { get; set; }
        public string SysDiy11 { get; set; }
        public string SysDiy12 { get; set; }
        public string SysDiy13 { get; set; }
        public string SysDiy14 { get; set; }
        public string SysDiy15 { get; set; }
        public string SysDiy16 { get; set; }
        public string efullnamecustom { get; set; }
        public string pfullnamecustom { get; set; }
        public string bfullnamecustom { get; set; }
        public string dfullnamecustom { get; set; }
        public string kfullnamecustom { get; set; }
        public string sfullnamecustom { get; set; }
        public Nullable<decimal> ChangeTotal { get; set; }
    }
}
