USE [SaleTools]
GO

INSERT INTO [dbo].[GoodInfo]
           ([Id]
           ,[GoodsNum]
           ,[BarCode]
           ,[MiddleCode]
           ,[BoxCode]
           ,[SupplierId]
           ,[SupplierNum]
           ,[SupplierName]
           ,[FirstTypeId]
           ,[FirstTypeName]
           ,[SecondTypeId]
           ,[SecondTypeName]
           ,[ThirdTYypeId]
           ,[ThirdTypeName]
           ,[GoodsTittle]
           ,[GoodsSubTittle]
           ,[BrandId]
           ,[BrandName]
           ,[RetailtPrice]
           ,[MarketPrice]
           ,[CostPrice]
           ,[Stock]
           ,[IsLockStork]
           ,[BoxSpec]
           ,[Spec]
           ,[Unit]
           ,[Weight]
           ,[Size]
           ,[ShelfLife]
           ,[MinCount]
           ,[LimitCount]
           ,[pic1]
           ,[pic2]
           ,[pic3]
           ,[pic4]
           ,[pic5]
           ,[KeyWord]
           ,[Detail]
           ,[CreateUserId]
           ,[CreateUserName]
           ,[IsDelete]
           ,[CreateTime]
           ,[LastUpdateTime]
           ,[SortId]
           ,[IsUpShelves]
           ,[ErpId]
           ,[BasePrice]
           ,[PriceForA]
           ,[PriceForB]
           ,[PriceForC]
           ,[PriceForD]
           ,[PriceForLianSuo])
     select 

           newid()
		   ,typeId
		   ,EntryCode
		   ,''
		   ,''
		   ,3
		   ,'00002'
		   ,'测试供应商2235'
		   ,'00000000-0000-0000-0000-000000000000'
		   ,''
           ,'00000000-0000-0000-0000-000000000000'
           ,''
           ,'00000000-0000-0000-0000-000000000000'
           ,''
           ,FullName
           ,Name
           ,'00000000-0000-0000-0000-000000000000'
           ,''
           ,preprice5
           ,preprice5
           ,recPrice
           ,-1
           ,0
           ,Standard
           ,Standard
           ,Unit1
           ,''
           ,''
           ,ValidDays
           ,1
           ,100
           ,''
          ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,'A77D5476-501F-4F50-A5AB-B364E8F92F21'
           ,'管理员'
           ,0
           ,CreateDate
           ,CreateDate
           ,SortID
           ,1
           ,typeId
           ,preprice1
           ,preprice1
           ,preprice2
           ,preprice3
           ,preprice4
           ,0 FROM [V3_DataTOP].[dbo].[ptype]

	